import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ErrorWrapper from "./error-wraper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description:
    "Generated by create next app, this data is stored in layout.txx of app directory",
};

// Main Function
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen antialiased`}
    >
      <body className="min-h-full  flex flex-col">
        <div>
          <header>
            <h1
              style={{ backgroundColor: "lightblue", padding: "2rem" }}
              className="text-3xl bg-amber-800 font-bold underline"
            >
              Header
            </h1>
          </header>
            {children}
          <footer >
            <h1
            style={{ justifyItems: "center", padding: "2rem" }}
              className="text-3xl bg-amber-500 font-bold underline"
            >
              Footer
            </h1>
          </footer>
        </div>
      </body>
    </html>
  );
}
