import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app, this data is stored in layout.txx of app directory",
  
};

export default function Home() {
  return (
    <>
   <h1 className="text-3xl font-bold underline">Hello world!</h1>
   <p><Link href='/'>Home</Link></p>
   <p><Link href = "/login">Login</Link></p>
   </>
  );
}
